### ISSUE TITLE
IndexOutOfBoundException

### ISSUE THREAD

**Issue by royalboyarchit** [andreasagap/MultiClients-Server#1]
Server Class : Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: 0
	at server.Server.main(Server.java:48)

Client Main Class : Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: 0
	at client.Client_main.main(Client_main.java:37)

Error arises at args[] in both Client and server main class;

**Comment by andreasagap** [comment]
Did you execute the server and client with the args?
Client takes for args  IP and Port.
Server takes for args only Port. 
You can run the programs from different command line, so:

- Server side's command line:  java -jar Server.jar 1234

- Client side's command line:  java -jar Client.jar localhost 1234
